name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      git_tag:
        description: 'Git tag to create'
        default: '$RANDOM'

jobs:
  push_git_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create and push git tag
      run: |
        TAG=${{ github.event.inputs.git_tag }}
#        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git tag $TAG
        git push origin $TAG
