name: 'Tag HEAD'
on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: 'Git tag to create'
        default: '$RANDOM'
jobs:
  push_git_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create and push git tag
      run: |
        TAG=${{ github.event.inputs.git_tag }}
        git tag $TAG
        git push origin $TAG
